# .github/workflows/deploy.yml
name: Build & Deploy Jekyll to Workers
on:
  push:
    branches: [main]      # adjust
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Ruby tool-chain for Jekyll
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: '3.3' }

      - run: |
          bundle install --without development test
          bundle exec jekyll build --future   # outputs to ./_site

      # Deploy Worker + static assets
      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command:   deploy      # picks up wrangler.toml and ships it
